name: stacy_frontend
description: 'A new Flutter project.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web_socket_channel: ^3.0.3
  fbroadcast: ^2.0.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  logging: ^1.3.0
  responsive_builder: ^0.7.1
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  http: ^1.4.0
  shared_preferences: ^2.5.3
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/welcome_plant.png
